language: java

jdk:
  - openjdk8

#script: ./mvnw clean install

cache:
  directories:
  - "$HOME/.m2"

jobs:
  include:
  - stage: Test
    jdk: openjdk8
    script: ./mvnw clean verify

  - stage: Deploy
    jdk: openjdk8
    script:
    - "./deploy.sh"

branches:
  only:
  - travis-integration

notifications:
  email:
  - info@techprimers.com


